"""made some changes in the TABLE RELATIONS

Revision ID: 60f620c57d1b
Revises: aecc0f9dbf83
Create Date: 2026-07-16 22:46:52.569958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60f620c57d1b'
down_revision: Union[str, Sequence[str], None] = 'aecc0f9dbf83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
    "companies",
    "founded_year",
    type_=sa.Integer(),
    postgresql_using="founded_year::integer"
)

    op.drop_constraint(op.f('recruiter_profile_company_id_key'), 'recruiter_profile', type_='unique')
    op.drop_constraint(op.f('recruiter_profile_user_id_key'), 'recruiter_profile', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('recruiter_profile_user_id_key'), 'recruiter_profile', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('recruiter_profile_company_id_key'), 'recruiter_profile', ['company_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('companies', 'founded_year',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
