"""added jobs and companies table

Revision ID: aecc0f9dbf83
Revises: ca31621ccf54
Create Date: 2026-07-16 20:41:32.617082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aecc0f9dbf83'
down_revision: Union[str, Sequence[str], None] = 'ca31621ccf54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('website', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('company_size', sa.String(), nullable=False),
    sa.Column('headquarters', sa.String(), nullable=False),
    sa.Column('founded_year', sa.String(), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('website')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_table('jobs',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('recruiter_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('employment_type', sa.Enum('INTERNSHIP', 'JOB', 'PERFORMANCE_BASED', name='employmenttype'), nullable=False),
    sa.Column('work_mode', sa.Enum('REMOTE', 'ON_SITE', 'HYBRID', name='workmode'), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('salary_min', sa.Float(), nullable=False),
    sa.Column('salary_max', sa.Float(), nullable=False),
    sa.Column('experience_required', sa.Integer(), nullable=False),
    sa.Column('vacancies', sa.Integer(), nullable=False),
    sa.Column('application_deadline', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'PAUSED', name='jobstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['recruiter_id'], ['recruiter_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id'),
    sa.UniqueConstraint('recruiter_id')
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_foreign_key(None, 'recruiter_profile', 'companies', ['company_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recruiter_profile', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
