"""create student profile table

Revision ID: bd30cc6e0449
Revises: a7e7e55eb8e1
Create Date: 2026-07-14 20:17:08.875790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd30cc6e0449'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studentS_profiles',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('university', sa.String(), nullable=False),
    sa.Column('degree', sa.String(), nullable=False),
    sa.Column('branch', sa.String(), nullable=False),
    sa.Column('graduation_year', sa.Integer(), nullable=False),
    sa.Column('cgpa', sa.Float(), nullable=False),
    sa.Column('github_url', sa.String(), nullable=False),
    sa.Column('linkedin_url', sa.String(), nullable=False),
    sa.Column('resume_url', sa.String(), nullable=False),
    sa.Column('profile_photo_url', sa.String(), nullable=False),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('expected_stipend', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studentS_profiles_id'), 'studentS_profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_studentS_profiles_id'), table_name='studentS_profiles')
    op.drop_table('studentS_profiles')
    # ### end Alembic commands ###
